# Generated by Django 5.1.2 on 2024-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='towork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=False)),
                ('is_published', models.BooleanField(default=0)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
