# Generated by Django 5.1.2 on 2024-10-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towork', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='towork',
            new_name='Article',
        ),
    ]
